### ISSUE TITLE
File is protected with IRM - can't open

### ISSUE THREAD

**Issue by DeanGross144** [microsoft/EntraIDGovernance-Training#31]
I can't open and save the 04 MEPM_PCI and remediation file, I can do this for all of the other files in this project, I am getting a request to enable Information rights Management and then this error
![image](https://github.com/microsoft/EntraIDGovernance-Training/assets/85760922/87d5243b-82a9-4f00-8fd5-bddcae634874)

**Comment by jorlopama** [comment]
Files has been updated. Please try again.
